# Setup
title:               tang-hi
tagline:             'tang-hi Blog'
description:         'some note writted by tang'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              tangdh 
  url:               http://tangdhcs.cn/
  email:             tangdhcs@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
