site_url: https://tang-hi.github.io
repo_url: https://github.com/tang-hi/tang-hi.github.io
theme:
  name: material
  palette:
    primary: blue grey
  features:
    - navigation.expand

site_name: tang-hi's blog

nav:
  - Paper Reading:
      - MapReduce: "paper/mapreduce.md"
